package presentacion;

import clases.IngresarVehiculoClase;
import clases.Vehiculo;
import datos.Conexion;
import java.security.Timestamp;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.IngresarVehiculoLog;


public class IngresarVehiculoGui extends javax.swing.JInternalFrame {

    DateFormat df = DateFormat.getDateInstance();
    
    IngresarVehiculoLog objIngresarVehiculoLog = new IngresarVehiculoLog();
    
    public IngresarVehiculoGui() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarIngresoVehiculo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreIngresoVehiculo = new javax.swing.JTextField();
        txtPlacaIngresoVehiculo = new javax.swing.JTextField();
        txtCedulaIngresoVehiculo = new javax.swing.JTextField();
        cmbTipoVehiculoIngresar = new javax.swing.JComboBox<>();
        cmbCascosIngresar = new javax.swing.JComboBox<>();
        btnEliminarIngresoVehiculo = new javax.swing.JButton();
        btnCancelarIngresoVehiculo = new javax.swing.JButton();
        btnModificarIngreseVehiculo = new javax.swing.JButton();
        txtfechaIngVehiculo = new javax.swing.JTextField();
        jdCalendarIngVeh = new com.toedter.calendar.JDateChooser();
        JIfondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ingresar Vehiculo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarIngresoVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarIngresoVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardarIngresoVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/guardar32.png"))); // NOI18N
        btnGuardarIngresoVehiculo.setText("Guardar");
        btnGuardarIngresoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarIngresoVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarIngresoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre del Propietario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*Placa del Vehiculo*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Cedula Propietario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        txtNombreIngresoVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtNombreIngresoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 150, -1));

        txtPlacaIngresoVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPlacaIngresoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 150, -1));

        txtCedulaIngresoVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtCedulaIngresoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 150, -1));

        cmbTipoVehiculoIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbTipoVehiculoIngresar.setForeground(new java.awt.Color(255, 0, 0));
        cmbTipoVehiculoIngresar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Seleccione Vehiculo*", "Carro", "Moto" }));
        cmbTipoVehiculoIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVehiculoIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipoVehiculoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 160, -1));

        cmbCascosIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCascosIngresar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cascos", "1", "2" }));
        cmbCascosIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCascosIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCascosIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        btnEliminarIngresoVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarIngresoVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminarIngresoVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar32..png"))); // NOI18N
        btnEliminarIngresoVehiculo.setText("Eliminar");
        getContentPane().add(btnEliminarIngresoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        btnCancelarIngresoVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarIngresoVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelarIngresoVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancelar300.png"))); // NOI18N
        btnCancelarIngresoVehiculo.setText("Cancelar");
        btnCancelarIngresoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarIngresoVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarIngresoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        btnModificarIngreseVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarIngreseVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificarIngreseVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/actualizar32.png"))); // NOI18N
        btnModificarIngreseVehiculo.setText("Modificar");
        btnModificarIngreseVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarIngreseVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarIngreseVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));
        getContentPane().add(txtfechaIngVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 70, -1));

        jdCalendarIngVeh.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        getContentPane().add(jdCalendarIngVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 150, -1));

        JIfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo parqueadero dia.jpg"))); // NOI18N
        JIfondo.setText("JIfondo");
        getContentPane().add(JIfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 626, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ComboBox para seleccionar la cantidad de cascos
    private void cmbCascosIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCascosIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCascosIngresarActionPerformed

    //Botón cancelar que limpia todos los campos
    private void btnCancelarIngresoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarIngresoVehiculoActionPerformed
       //Limpiar campos 
        txtPlacaIngresoVehiculo.setText("");
        txtCedulaIngresoVehiculo.setText("");
        txtNombreIngresoVehiculo.setText("");
        txtPlacaIngresoVehiculo.requestFocusInWindow();
    }//GEN-LAST:event_btnCancelarIngresoVehiculoActionPerformed

    //Para habilitar o deshabilitar el comboBox del tipo de vehiculo, si se selecciona la opción (moto).
    private void cmbTipoVehiculoIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVehiculoIngresarActionPerformed
       
        int i = cmbTipoVehiculoIngresar.getSelectedIndex();
        
        if(i == 2){ 
           cmbCascosIngresar.setEnabled(true);
                   }else{
            cmbCascosIngresar.setEnabled(false);
        }
    }//GEN-LAST:event_cmbTipoVehiculoIngresarActionPerformed

    //En proceso
    private void btnModificarIngreseVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarIngreseVehiculoActionPerformed
       
    }//GEN-LAST:event_btnModificarIngreseVehiculoActionPerformed

    //Botón encargado de guardar los datos digitados por el cliente
    //con las restricciones de que se ingrese de forma obligatoria la placa y se seleccione el tipo de vehiculo
    private void btnGuardarIngresoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIngresoVehiculoActionPerformed
        //validar que los campos obligatorios esten dijitados 
        
        if(txtPlacaIngresoVehiculo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar el numero de PLACA");
            txtPlacaIngresoVehiculo.requestFocusInWindow();
            return;
        }
        
         if(cmbTipoVehiculoIngresar.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane,"Debe seleccionar tipo de VEHICULO");
            txtPlacaIngresoVehiculo.requestFocusInWindow();
            return;
        }
         
         IngresarVehiculoLog objIngresarVehiculoLog = new IngresarVehiculoLog();
         
         String placa = txtPlacaIngresoVehiculo.getText();
         String ccPropietario = txtCedulaIngresoVehiculo.getText();
         String nomPropietario = txtNombreIngresoVehiculo.getText();
         int tipoVehiculo = cmbTipoVehiculoIngresar.getSelectedIndex();
         int cascos = cmbCascosIngresar.getSelectedIndex();
         Date fecha = jdCalendarIngVeh.getDate();
         
        ///////////////////////fecha///////////////////////// 
        Date fechaActual = new Date();
        jdCalendarIngVeh.setDate(fechaActual);
        System.out.println("fecha :"+ fechaActual);

        txtfechaIngVehiculo.setText(df.format(fechaActual));
         System.out.println("fecha d :"+ fechaActual);
        String fechaConvertida = df.format(fechaActual);
        ////////////////////////////////hhhh//////////////////////////////////
        
        //Crear objeto Vehiculo
        Vehiculo objVehiculo = new Vehiculo(placa,ccPropietario,nomPropietario,tipoVehiculo,cascos);
        objIngresarVehiculoLog.agregar(objVehiculo,fecha);
        JOptionPane.showMessageDialog(rootPane,"Vehiculo ingresado correctamente");
        
       
         
        //Limpiar campos 
        txtPlacaIngresoVehiculo.setText("");
        txtCedulaIngresoVehiculo.setText("");
        txtNombreIngresoVehiculo.setText("");
        cmbTipoVehiculoIngresar.setSelectedIndex(0);
        cmbCascosIngresar.setSelectedIndex(0);
        txtPlacaIngresoVehiculo.requestFocusInWindow();
        
    }//GEN-LAST:event_btnGuardarIngresoVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JIfondo;
    private javax.swing.JButton btnCancelarIngresoVehiculo;
    private javax.swing.JButton btnEliminarIngresoVehiculo;
    private javax.swing.JButton btnGuardarIngresoVehiculo;
    private javax.swing.JButton btnModificarIngreseVehiculo;
    private javax.swing.JComboBox<String> cmbCascosIngresar;
    private javax.swing.JComboBox<String> cmbTipoVehiculoIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser jdCalendarIngVeh;
    private javax.swing.JTextField txtCedulaIngresoVehiculo;
    public static javax.swing.JTextField txtNombreIngresoVehiculo;
    private javax.swing.JTextField txtPlacaIngresoVehiculo;
    private javax.swing.JTextField txtfechaIngVehiculo;
    // End of variables declaration//GEN-END:variables
}
