package presentacion;

public class PrincipalGui extends javax.swing.JFrame {
    /**
     * Página Principal, una vez se haya logueado.
     */
    public PrincipalGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuVehiculo = new javax.swing.JMenu();
        mnuVehiculoIngresoVehiculo = new javax.swing.JMenuItem();
        mnuVehiculoRetirarVehiculo = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenu();
        mnuUsuarioModificarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpnEscritorio.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout dpnEscritorioLayout = new javax.swing.GroupLayout(dpnEscritorio);
        dpnEscritorio.setLayout(dpnEscritorioLayout);
        dpnEscritorioLayout.setHorizontalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        dpnEscritorioLayout.setVerticalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        mnuVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/vehiculo32.png"))); // NOI18N
        mnuVehiculo.setText("Vehiculo");

        mnuVehiculoIngresoVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/ingresar parqueadero 32.png"))); // NOI18N
        mnuVehiculoIngresoVehiculo.setText("Ingreso de Vehiculo");
        mnuVehiculoIngresoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVehiculoIngresoVehiculoActionPerformed(evt);
            }
        });
        mnuVehiculo.add(mnuVehiculoIngresoVehiculo);

        mnuVehiculoRetirarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir del parqueadero 32.png"))); // NOI18N
        mnuVehiculoRetirarVehiculo.setText("Retirar Vehiculo");
        mnuVehiculo.add(mnuVehiculoRetirarVehiculo);

        jMenuBar1.add(mnuVehiculo);

        mnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/usuario32.png"))); // NOI18N
        mnuUsuario.setText("Usuario");

        mnuUsuarioModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/ingresar usuario 32.png"))); // NOI18N
        mnuUsuarioModificarUsuario.setText("Ingresar Usuario");
        mnuUsuario.add(mnuUsuarioModificarUsuario);

        jMenuBar1.add(mnuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuVehiculoIngresoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculoIngresoVehiculoActionPerformed
        
        //Instancia de la interfaz para registrar el ingreso del vehiculo
        IngresarVehiculoGui objIngresarVehiculoGui = new IngresarVehiculoGui();
        
        dpnEscritorio.add(objIngresarVehiculoGui);
        
        objIngresarVehiculoGui.show();
    }//GEN-LAST:event_mnuVehiculoIngresoVehiculoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuUsuario;
    private javax.swing.JMenuItem mnuUsuarioModificarUsuario;
    private javax.swing.JMenu mnuVehiculo;
    private javax.swing.JMenuItem mnuVehiculoIngresoVehiculo;
    private javax.swing.JMenuItem mnuVehiculoRetirarVehiculo;
    // End of variables declaration//GEN-END:variables
}
